import { existsSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const dataRoot = new URL('../src/data/', import.meta.url);
const recordsPerPart = 100;
const generatedHeader = '// Generated by scripts/classification-index.mjs; edit individual JSON records.';
const indexes = [
  ['entities', 'EntityClassification', 'ENTITIES'],
  ['attack-classifications', 'AttackClassification', 'ATTACKS'],
];

function renderPart(files, folder, type, exportName) {
  const imports = files.map((name, index) => `import record${index} from './${folder}/${name}' with { type: 'json' };`);
  const entries = files.map((name, index) => `  ${JSON.stringify(name.slice(0, -5))}: record${index},`);
  return [
    generatedHeader,
    `import type { ${type} } from '../classificationTypes';`,
    ...imports,
    '',
    `export const ${exportName} = {`,
    ...entries,
    `} as Record<string, ${type}>;`,
    '',
  ].join('\n');
}

// Keep source records readable and independently reviewable; regenerate after adding an ID.
export function buildClassificationIndexes(root = dataRoot) {
  const output = new Map();
  for (const [folder, type, exportName] of indexes) {
    const files = readdirSync(new URL(`${folder}/`, root)).filter(name => name.endsWith('.json')).sort();
    const parts = [];
    for (let start = 0; start < files.length; start += recordsPerPart) {
      const partExport = `${exportName}_PART_${parts.length + 1}`;
      const partFile = `${folder}-index-part-${parts.length + 1}.ts`;
      output.set(partFile, renderPart(files.slice(start, start + recordsPerPart), folder, type, partExport));
      parts.push({ file: partFile, name: partExport });
    }
    output.set(`${folder}-index.ts`, [
      generatedHeader,
      `import type { ${type} } from '../classificationTypes';`,
      ...parts.map(part => `import { ${part.name} } from './${part.file}';`),
      '',
      `export const ${exportName} = {`,
      ...parts.map(part => `  ...${part.name},`),
      `} as Record<string, ${type}>;`,
      '',
    ].join('\n'));
  }
  return output;
}

export function prepareClassificationIndexes({ root = dataRoot, check = false } = {}) {
  const output = buildClassificationIndexes(root);
  const obsolete = readdirSync(root).filter(name => (
    indexes.some(([folder]) => name.startsWith(`${folder}-index-part-`) && name.endsWith('.ts'))
    && !output.has(name)
  ));
  if (check && obsolete.length) {
    throw new Error(`Obsolete classification index parts: ${obsolete.join(', ')}; run node scripts/classification-index.mjs`);
  }
  for (const [name, content] of output) {
    const target = new URL(name, root);
    if (check) {
      if (!existsSync(target) || readFileSync(target, 'utf8') !== content) {
        throw new Error(`Missing or stale classification index: ${name}; run node scripts/classification-index.mjs`);
      }
    } else {
      writeFileSync(target, content);
    }
  }
  if (!check) {
    for (const name of obsolete) unlinkSync(new URL(name, root));
  }
  return output;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  prepareClassificationIndexes({ check: process.argv.includes('--check') });
}
