import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
const root = new URL('../src/data/', import.meta.url);
// Keep source records readable and independently reviewable; regenerate after adding an ID.
for (const [folder, type, exportName] of [['entities', 'EntityClassification', 'ENTITIES'], ['attack-classifications', 'AttackClassification', 'ATTACKS']]) {
  const files = readdirSync(new URL(`${folder}/`, root)).filter(name => name.endsWith('.json')).sort();
  const imports = files.map((name, index) => `import record${index} from './${folder}/${name}' with { type: 'json' };`).join('\n');
  const entries = files.map((name, index) => `  ${JSON.stringify(name.slice(0, -5))}: record${index},`).join('\n');
  const content = `// Generated by scripts/classification-index.mjs; edit individual JSON records.\nimport type { ${type} } from '../classificationTypes';\n${imports}\nexport const ${exportName} = {\n${entries}\n} as Record<string, ${type}>;\n`;
  const target = new URL(`${folder}-index.ts`, root);
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== content) throw new Error(`${folder} index is stale; run node scripts/classification-index.mjs`);
  } else writeFileSync(target, content);
}
