import { chromium, devices } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { loadData } from './data-status.mjs';
import { DEFAULT_CLASSIFICATION, getAttack, getEntities, matchesClassification } from '../src/lib/classification.ts';
import { filterIncidents } from '../src/lib/incidents.ts';
const url = process.env.UI_URL ?? 'http://127.0.0.1:4173/';
const output = process.env.UI_OUTPUT ?? 'artifacts/ui';
mkdirSync(output, { recursive: true });
const { incidents } = loadData();
const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {});
const results = [];
const errors = [];
const check = (name, value) => { assert.ok(value, name); results.push(name); };
const label = { industry: '被害対象企業の業種', manufacturingType: '製造業の細分類', listingStatus: '被害対象企業の上場区分', attackKind: '攻撃・事象の種類', initialAccess: '初期侵入経路', confidence: '攻撃・経路の確度' };
const reset = page => page.getByRole('button', { name: 'すべての絞り込みを解除', exact: true }).click();
async function count(page, expected) { await page.waitForFunction(n => document.querySelectorAll('.incident-card').length === n, expected); }
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 980 } });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url); await count(page, incidents.length);
  await page.locator('.classification-filters summary').click();
  const selected = { ...DEFAULT_CLASSIFICATION, industry: 'manufacturing', listingStatus: 'listed', attackKind: 'ransomware', confidence: 'confirmed' };
  for (const key of ['industry', 'listingStatus', 'attackKind', 'confidence']) await page.getByLabel(label[key], { exact: true }).selectOption(selected[key]);
  const expected = incidents.filter(item => matchesClassification(item, selected));
  check('manufacturing, listed and confirmed ransomware intersection is nonempty', expected.length > 0);
  await count(page, expected.length);
  check('combined filters show exact expected IDs through company names', (await page.locator('.incident-card strong').allTextContents()).every(name => expected.some(item => item.company === name)));
  check('classification count is announced', (await page.locator('.classification-summary').innerText()).includes(`表示中 ${expected.length}件`));
  const sharedUrl = page.url();
  await page.reload(); await count(page, expected.length);
  check('share URL survives reload and collapsed controls preserve values', await page.getByLabel(label.industry, { exact: true }).inputValue() === 'manufacturing');
  await page.getByRole('button', { name: 'ライブラリの脆弱性', exact: true }).click();
  await page.getByLabel('ライブラリ・脆弱性を検索').waitFor();
  check('vulnerability category has no company classification controls', await page.locator('.classification-controls').count() === 0);
  await page.goBack(); await count(page, expected.length);
  check('Back restores classification route', page.url().includes('industry=manufacturing'));
  await page.goForward();
  await page.waitForFunction(() => new URLSearchParams(location.hash.slice(1)).get('kind') === 'vulnerability');
  await page.goto(sharedUrl); await count(page, expected.length);
  await reset(page); await count(page, incidents.length);
  check('reset clears every new URL filter', Object.keys(label).every(key => !new URL(page.url()).hash.includes(`${key}=`)));
  const target = incidents.find(item => getEntities(item.id).some(entity => entity.manufacturingType === 'electronics') && getAttack(item.id).attackKind === 'ransomware');
  check('representative electronics ransomware record exists', !!target);
  await page.getByRole('textbox', { name: '企業名・事案を検索', exact: true }).fill(target.company);
  await page.locator('.classification-filters summary').click();
  await page.getByLabel(label.manufacturingType, { exact: true }).selectOption('electronics');
  const searchExpected = filterIncidents(incidents, ['leak', 'outage', 'unauthorizedAccess'], 'all', target.company).filter(item => matchesClassification(item, { ...DEFAULT_CLASSIFICATION, manufacturingType: 'electronics' }));
  await count(page, searchExpected.length);
  await page.locator('.incident-card').first().click();
  await page.locator('.drawer.open .classification-detail').waitFor();
  check('detail shows evidence and current listing basis', (await page.locator('.drawer').innerText()).includes('上場区分') && (await page.locator('.drawer').innerText()).includes('初期侵入経路'));
  await page.getByRole('textbox', { name: '企業名・事案を検索', exact: true }).fill('no-match-classification-zz');
  await count(page, 0);
  await page.waitForFunction(() => !document.querySelector('.drawer.open'));
  check('filtering selected incident out closes the drawer', await page.locator('.drawer.open').count() === 0);
  check('zero results are explicit', await page.getByText('条件に合う事案がありません', { exact: true }).isVisible());
  await reset(page); await count(page, incidents.length);
  await reset(page); await count(page, incidents.length);
  await page.screenshot({ path: `${output}/classification-desktop.png`, fullPage: true });
  const mobile = await browser.newPage({ ...devices['Pixel 5'] });
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(`${url}#attackKind=ransomware&confidence=confirmed`);
  const ransomCount = incidents.filter(item => getAttack(item.id).attackKind === 'ransomware' && getAttack(item.id).attackKindStatus === 'confirmed').length;
  await count(mobile, ransomCount);
  await mobile.getByRole('button', { name: /^事案一覧/ }).click();
  check('mobile share URL and list view have exact ransomware count', await mobile.locator('.incident-card').count() === ransomCount);
  await mobile.locator('.classification-filters summary').click();
  await mobile.getByLabel(label.attackKind, { exact: true }).selectOption('unknown');
  await mobile.getByLabel(label.confidence, { exact: true }).selectOption('all');
  await count(mobile, incidents.filter(item => getAttack(item.id).attackKind === 'unknown').length);
  check('mobile expanded filters have no page overflow', await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await mobile.locator('.classification-filters summary').click();
  await reset(mobile); await count(mobile, incidents.length);
  await mobile.screenshot({ path: `${output}/classification-mobile.png`, fullPage: true });
  check('no browser runtime errors', errors.length === 0);
  writeFileSync(`${output}/classification-results.json`, JSON.stringify({ results, errors }, null, 2));
  console.log(`Classification UI: ${results.length} checks passed`);
} finally { await browser.close(); }
