// Generated by scripts/classification-index.mjs; edit individual JSON records.
import type { AttackClassification } from '../classificationTypes';
import record0 from './attack-classifications/rakuten-drive-2026.json' with { type: 'json' };
import record1 from './attack-classifications/resorttrust-2026.json' with { type: 'json' };
import record2 from './attack-classifications/restar-group-2023.json' with { type: 'json' };
import record3 from './attack-classifications/ricoh-drive-2023.json' with { type: 'json' };
import record4 from './attack-classifications/sagawa-tracking-2026.json' with { type: 'json' };
import record5 from './attack-classifications/sakura-investigation-2026.json' with { type: 'json' };
import record6 from './attack-classifications/sammy-777conpass-2026.json' with { type: 'json' };
import record7 from './attack-classifications/scala-iask-2026.json' with { type: 'json' };
import record8 from './attack-classifications/seed-2022.json' with { type: 'json' };
import record9 from './attack-classifications/seicomart-app-2026.json' with { type: 'json' };
import record10 from './attack-classifications/seidensha-2026.json' with { type: 'json' };
import record11 from './attack-classifications/seiko-2023.json' with { type: 'json' };
import record12 from './attack-classifications/sevennet-2023.json' with { type: 'json' };
import record13 from './attack-classifications/sharp-cocoro-2024.json' with { type: 'json' };
import record14 from './attack-classifications/shinchosha-investigation-2025.json' with { type: 'json' };
import record15 from './attack-classifications/shirohato-2025.json' with { type: 'json' };
import record16 from './attack-classifications/skyticket-bus-2026.json' with { type: 'json' };
import record17 from './attack-classifications/skyticket-management-2026.json' with { type: 'json' };
import record18 from './attack-classifications/skyticket-server-2026.json' with { type: 'json' };
import record19 from './attack-classifications/sogo-2024.json' with { type: 'json' };
import record20 from './attack-classifications/solpac-2023.json' with { type: 'json' };
import record21 from './attack-classifications/sompo-japan-web-2025.json' with { type: 'json' };
import record22 from './attack-classifications/sougyo-2024.json' with { type: 'json' };
import record23 from './attack-classifications/sourcenext-shop-2023.json' with { type: 'json' };
import record24 from './attack-classifications/surugaya-payment-2025.json' with { type: 'json' };
import record25 from './attack-classifications/takamiya-2022.json' with { type: 'json' };
import record26 from './attack-classifications/takara-belmont-2024.json' with { type: 'json' };
import record27 from './attack-classifications/tci-us-2022.json' with { type: 'json' };
import record28 from './attack-classifications/teikoku-databank-2023.json' with { type: 'json' };
import record29 from './attack-classifications/temairazu-2026.json' with { type: 'json' };
import record30 from './attack-classifications/thinca-marketing-sites-2026.json' with { type: 'json' };
import record31 from './attack-classifications/tokyo-gas-tges-2024.json' with { type: 'json' };
import record32 from './attack-classifications/tokyo-metro-metpo-2026.json' with { type: 'json' };
import record33 from './attack-classifications/tokyu-toko-foods-2024.json' with { type: 'json' };
import record34 from './attack-classifications/tomoe-shokai-2024.json' with { type: 'json' };
import record35 from './attack-classifications/toyota-connected-cloud-2023.json' with { type: 'json' };
import record36 from './attack-classifications/toyota-mobility-bookingcar-2024.json' with { type: 'json' };
import record37 from './attack-classifications/voising-bi-tool-2026.json' with { type: 'json' };
import record38 from './attack-classifications/wantedly-2024.json' with { type: 'json' };
import record39 from './attack-classifications/whiteessence-2026.json' with { type: 'json' };
import record40 from './attack-classifications/world-wide-system-ses-2026.json' with { type: 'json' };
import record41 from './attack-classifications/y4-health-service-2023.json' with { type: 'json' };
import record42 from './attack-classifications/zeon-2023.json' with { type: 'json' };
import record43 from './attack-classifications/zojirushi-2026-05-15.json' with { type: 'json' };

export const ATTACKS_PART_2 = {
  "rakuten-drive-2026": record0,
  "resorttrust-2026": record1,
  "restar-group-2023": record2,
  "ricoh-drive-2023": record3,
  "sagawa-tracking-2026": record4,
  "sakura-investigation-2026": record5,
  "sammy-777conpass-2026": record6,
  "scala-iask-2026": record7,
  "seed-2022": record8,
  "seicomart-app-2026": record9,
  "seidensha-2026": record10,
  "seiko-2023": record11,
  "sevennet-2023": record12,
  "sharp-cocoro-2024": record13,
  "shinchosha-investigation-2025": record14,
  "shirohato-2025": record15,
  "skyticket-bus-2026": record16,
  "skyticket-management-2026": record17,
  "skyticket-server-2026": record18,
  "sogo-2024": record19,
  "solpac-2023": record20,
  "sompo-japan-web-2025": record21,
  "sougyo-2024": record22,
  "sourcenext-shop-2023": record23,
  "surugaya-payment-2025": record24,
  "takamiya-2022": record25,
  "takara-belmont-2024": record26,
  "tci-us-2022": record27,
  "teikoku-databank-2023": record28,
  "temairazu-2026": record29,
  "thinca-marketing-sites-2026": record30,
  "tokyo-gas-tges-2024": record31,
  "tokyo-metro-metpo-2026": record32,
  "tokyu-toko-foods-2024": record33,
  "tomoe-shokai-2024": record34,
  "toyota-connected-cloud-2023": record35,
  "toyota-mobility-bookingcar-2024": record36,
  "voising-bi-tool-2026": record37,
  "wantedly-2024": record38,
  "whiteessence-2026": record39,
  "world-wide-system-ses-2026": record40,
  "y4-health-service-2023": record41,
  "zeon-2023": record42,
  "zojirushi-2026-05-15": record43,
} as Record<string, AttackClassification>;
