// Generated by scripts/classification-index.mjs; edit individual JSON records.
import type { AttackClassification } from '../classificationTypes';
import { ATTACKS_PART_1 } from './attack-classifications-index-part-1.ts';
import { ATTACKS_PART_2 } from './attack-classifications-index-part-2.ts';

export const ATTACKS = {
  ...ATTACKS_PART_1,
  ...ATTACKS_PART_2,
} as Record<string, AttackClassification>;
