// Generated by scripts/classification-index.mjs; edit individual JSON records.
import type { AttackClassification } from '../classificationTypes';
import record0 from './attack-classifications/adastria-2023.json' with { type: 'json' };
import record1 from './attack-classifications/aflac-2026.json' with { type: 'json' };
import record2 from './attack-classifications/ainokaze-toyama-2026.json' with { type: 'json' };
import record3 from './attack-classifications/aizawa-am-2024.json' with { type: 'json' };
import record4 from './attack-classifications/applynow-2026.json' with { type: 'json' };
import record5 from './attack-classifications/asahi-2025.json' with { type: 'json' };
import record6 from './attack-classifications/askul-2025.json' with { type: 'json' };
import record7 from './attack-classifications/atex-2024.json' with { type: 'json' };
import record8 from './attack-classifications/avant-disclosure-2023.json' with { type: 'json' };
import record9 from './attack-classifications/bilcom-2024.json' with { type: 'json' };
import record10 from './attack-classifications/casio-2024.json' with { type: 'json' };
import record11 from './attack-classifications/casio-classpad-2023.json' with { type: 'json' };
import record12 from './attack-classifications/charm-2026.json' with { type: 'json' };
import record13 from './attack-classifications/chuden-2026.json' with { type: 'json' };
import record14 from './attack-classifications/cress-tech-2024.json' with { type: 'json' };
import record15 from './attack-classifications/ctc-subcontractor-2024.json' with { type: 'json' };
import record16 from './attack-classifications/docomo-plala-hikari-2023.json' with { type: 'json' };
import record17 from './attack-classifications/estore-2026-08-01.json' with { type: 'json' };
import record18 from './attack-classifications/etc-meisai-2023.json' with { type: 'json' };
import record19 from './attack-classifications/fujikura-2024.json' with { type: 'json' };
import record20 from './attack-classifications/fujitsu-2024.json' with { type: 'json' };
import record21 from './attack-classifications/furuno-electric-2025.json' with { type: 'json' };
import record22 from './attack-classifications/furuno-systems-2022.json' with { type: 'json' };
import record23 from './attack-classifications/ginpo-pack-2023.json' with { type: 'json' };
import record24 from './attack-classifications/glory-2023.json' with { type: 'json' };
import record25 from './attack-classifications/harada-beer-engawa-2026.json' with { type: 'json' };
import record26 from './attack-classifications/his-2026.json' with { type: 'json' };
import record27 from './attack-classifications/hoya-2024.json' with { type: 'json' };
import record28 from './attack-classifications/huistenbosch-2025.json' with { type: 'json' };
import record29 from './attack-classifications/hulu-credential-stuffing-2025.json' with { type: 'json' };
import record30 from './attack-classifications/icc-2026-05-19.json' with { type: 'json' };
import record31 from './attack-classifications/idc-frontier-2026.json' with { type: 'json' };
import record32 from './attack-classifications/iij-securemx-2025.json' with { type: 'json' };
import record33 from './attack-classifications/iseto-2024.json' with { type: 'json' };
import record34 from './attack-classifications/ites-2023.json' with { type: 'json' };
import record35 from './attack-classifications/jcom-mesh-wifi-2023.json' with { type: 'json' };
import record36 from './attack-classifications/jtech-rokkasho-2023.json' with { type: 'json' };
import record37 from './attack-classifications/kadokawa-2024.json' with { type: 'json' };
import record38 from './attack-classifications/kanamoto-2024.json' with { type: 'json' };
import record39 from './attack-classifications/kantsu-2024.json' with { type: 'json' };
import record40 from './attack-classifications/kddi-isp-mail-2026.json' with { type: 'json' };
import record41 from './attack-classifications/kinokuniya-fujisan-delivery-2023.json' with { type: 'json' };
import record42 from './attack-classifications/kokuyo-2023.json' with { type: 'json' };
import record43 from './attack-classifications/kurashiki-hampu-2023.json' with { type: 'json' };
import record44 from './attack-classifications/kyusai-callcenter-2025.json' with { type: 'json' };
import record45 from './attack-classifications/laurel-2025.json' with { type: 'json' };
import record46 from './attack-classifications/line-yahoo-2023.json' with { type: 'json' };
import record47 from './attack-classifications/livable-insider-2024.json' with { type: 'json' };
import record48 from './attack-classifications/mazda-2026-03-19.json' with { type: 'json' };
import record49 from './attack-classifications/mimaru-asakusa-booking-2023.json' with { type: 'json' };
import record50 from './attack-classifications/mitsubishi-home-2024.json' with { type: 'json' };
import record51 from './attack-classifications/mks-shalom-2023.json' with { type: 'json' };
import record52 from './attack-classifications/moneyforward-2026-05-01.json' with { type: 'json' };
import record53 from './attack-classifications/morinaga-confectionery-2024.json' with { type: 'json' };
import record54 from './attack-classifications/nagoya-port-nuts-2023.json' with { type: 'json' };
import record55 from './attack-classifications/naniwa-pump-2024.json' with { type: 'json' };
import record56 from './attack-classifications/nichirei-2026.json' with { type: 'json' };
import record57 from './attack-classifications/nidec-instruments-2024.json' with { type: 'json' };
import record58 from './attack-classifications/nidec-precision-vietnam-2024.json' with { type: 'json' };
import record59 from './attack-classifications/nikkei-smartclip-2022.json' with { type: 'json' };
import record60 from './attack-classifications/nipro-china-2023.json' with { type: 'json' };
import record61 from './attack-classifications/nssol-2025.json' with { type: 'json' };
import record62 from './attack-classifications/ntt-business-solutions-2023.json' with { type: 'json' };
import record63 from './attack-classifications/ntt-com-order-2025.json' with { type: 'json' };
import record64 from './attack-classifications/oiles-2024.json' with { type: 'json' };
import record65 from './attack-classifications/park24-timescar-2026.json' with { type: 'json' };
import record66 from './attack-classifications/prtimes-2025.json' with { type: 'json' };
import record67 from './attack-classifications/restar-group-2023.json' with { type: 'json' };
import record68 from './attack-classifications/ricoh-drive-2023.json' with { type: 'json' };
import record69 from './attack-classifications/sakura-investigation-2026.json' with { type: 'json' };
import record70 from './attack-classifications/seed-2022.json' with { type: 'json' };
import record71 from './attack-classifications/seiko-2023.json' with { type: 'json' };
import record72 from './attack-classifications/sevennet-2023.json' with { type: 'json' };
import record73 from './attack-classifications/sharp-cocoro-2024.json' with { type: 'json' };
import record74 from './attack-classifications/shinchosha-investigation-2025.json' with { type: 'json' };
import record75 from './attack-classifications/shirohato-2025.json' with { type: 'json' };
import record76 from './attack-classifications/sogo-2024.json' with { type: 'json' };
import record77 from './attack-classifications/solpac-2023.json' with { type: 'json' };
import record78 from './attack-classifications/sompo-japan-web-2025.json' with { type: 'json' };
import record79 from './attack-classifications/sougyo-2024.json' with { type: 'json' };
import record80 from './attack-classifications/sourcenext-shop-2023.json' with { type: 'json' };
import record81 from './attack-classifications/surugaya-payment-2025.json' with { type: 'json' };
import record82 from './attack-classifications/takamiya-2022.json' with { type: 'json' };
import record83 from './attack-classifications/takara-belmont-2024.json' with { type: 'json' };
import record84 from './attack-classifications/tci-us-2022.json' with { type: 'json' };
import record85 from './attack-classifications/teikoku-databank-2023.json' with { type: 'json' };
import record86 from './attack-classifications/tokyo-gas-tges-2024.json' with { type: 'json' };
import record87 from './attack-classifications/tokyu-toko-foods-2024.json' with { type: 'json' };
import record88 from './attack-classifications/tomoe-shokai-2024.json' with { type: 'json' };
import record89 from './attack-classifications/toyota-connected-cloud-2023.json' with { type: 'json' };
import record90 from './attack-classifications/toyota-mobility-bookingcar-2024.json' with { type: 'json' };
import record91 from './attack-classifications/wantedly-2024.json' with { type: 'json' };
import record92 from './attack-classifications/y4-health-service-2023.json' with { type: 'json' };
import record93 from './attack-classifications/zeon-2023.json' with { type: 'json' };
import record94 from './attack-classifications/zojirushi-2026-05-15.json' with { type: 'json' };
export const ATTACKS = {
  "adastria-2023": record0,
  "aflac-2026": record1,
  "ainokaze-toyama-2026": record2,
  "aizawa-am-2024": record3,
  "applynow-2026": record4,
  "asahi-2025": record5,
  "askul-2025": record6,
  "atex-2024": record7,
  "avant-disclosure-2023": record8,
  "bilcom-2024": record9,
  "casio-2024": record10,
  "casio-classpad-2023": record11,
  "charm-2026": record12,
  "chuden-2026": record13,
  "cress-tech-2024": record14,
  "ctc-subcontractor-2024": record15,
  "docomo-plala-hikari-2023": record16,
  "estore-2026-08-01": record17,
  "etc-meisai-2023": record18,
  "fujikura-2024": record19,
  "fujitsu-2024": record20,
  "furuno-electric-2025": record21,
  "furuno-systems-2022": record22,
  "ginpo-pack-2023": record23,
  "glory-2023": record24,
  "harada-beer-engawa-2026": record25,
  "his-2026": record26,
  "hoya-2024": record27,
  "huistenbosch-2025": record28,
  "hulu-credential-stuffing-2025": record29,
  "icc-2026-05-19": record30,
  "idc-frontier-2026": record31,
  "iij-securemx-2025": record32,
  "iseto-2024": record33,
  "ites-2023": record34,
  "jcom-mesh-wifi-2023": record35,
  "jtech-rokkasho-2023": record36,
  "kadokawa-2024": record37,
  "kanamoto-2024": record38,
  "kantsu-2024": record39,
  "kddi-isp-mail-2026": record40,
  "kinokuniya-fujisan-delivery-2023": record41,
  "kokuyo-2023": record42,
  "kurashiki-hampu-2023": record43,
  "kyusai-callcenter-2025": record44,
  "laurel-2025": record45,
  "line-yahoo-2023": record46,
  "livable-insider-2024": record47,
  "mazda-2026-03-19": record48,
  "mimaru-asakusa-booking-2023": record49,
  "mitsubishi-home-2024": record50,
  "mks-shalom-2023": record51,
  "moneyforward-2026-05-01": record52,
  "morinaga-confectionery-2024": record53,
  "nagoya-port-nuts-2023": record54,
  "naniwa-pump-2024": record55,
  "nichirei-2026": record56,
  "nidec-instruments-2024": record57,
  "nidec-precision-vietnam-2024": record58,
  "nikkei-smartclip-2022": record59,
  "nipro-china-2023": record60,
  "nssol-2025": record61,
  "ntt-business-solutions-2023": record62,
  "ntt-com-order-2025": record63,
  "oiles-2024": record64,
  "park24-timescar-2026": record65,
  "prtimes-2025": record66,
  "restar-group-2023": record67,
  "ricoh-drive-2023": record68,
  "sakura-investigation-2026": record69,
  "seed-2022": record70,
  "seiko-2023": record71,
  "sevennet-2023": record72,
  "sharp-cocoro-2024": record73,
  "shinchosha-investigation-2025": record74,
  "shirohato-2025": record75,
  "sogo-2024": record76,
  "solpac-2023": record77,
  "sompo-japan-web-2025": record78,
  "sougyo-2024": record79,
  "sourcenext-shop-2023": record80,
  "surugaya-payment-2025": record81,
  "takamiya-2022": record82,
  "takara-belmont-2024": record83,
  "tci-us-2022": record84,
  "teikoku-databank-2023": record85,
  "tokyo-gas-tges-2024": record86,
  "tokyu-toko-foods-2024": record87,
  "tomoe-shokai-2024": record88,
  "toyota-connected-cloud-2023": record89,
  "toyota-mobility-bookingcar-2024": record90,
  "wantedly-2024": record91,
  "y4-health-service-2023": record92,
  "zeon-2023": record93,
  "zojirushi-2026-05-15": record94,
} as Record<string, AttackClassification>;
