// Generated by scripts/classification-index.mjs; edit individual JSON records.
import type { EntityClassification } from '../classificationTypes';
import record0 from './entities/2rinkan-yellowhat.json' with { type: 'json' };
import record1 from './entities/abahouse-international.json' with { type: 'json' };
import record2 from './entities/adastria.json' with { type: 'json' };
import record3 from './entities/adventure.json' with { type: 'json' };
import record4 from './entities/aflac-japan.json' with { type: 'json' };
import record5 from './entities/ainokaze-toyama.json' with { type: 'json' };
import record6 from './entities/aiphone-australia.json' with { type: 'json' };
import record7 from './entities/aizawa-am.json' with { type: 'json' };
import record8 from './entities/applynow.json' with { type: 'json' };
import record9 from './entities/asahi.json' with { type: 'json' };
import record10 from './entities/askul.json' with { type: 'json' };
import record11 from './entities/atex.json' with { type: 'json' };
import record12 from './entities/bilcom.json' with { type: 'json' };
import record13 from './entities/bookoff-unnamed-subsidiary.json' with { type: 'json' };
import record14 from './entities/casio.json' with { type: 'json' };
import record15 from './entities/charm.json' with { type: 'json' };
import record16 from './entities/chuden.json' with { type: 'json' };
import record17 from './entities/citizen-watch.json' with { type: 'json' };
import record18 from './entities/coconala.json' with { type: 'json' };
import record19 from './entities/commune.json' with { type: 'json' };
import record20 from './entities/core-concept-technologies.json' with { type: 'json' };
import record21 from './entities/cosmos-hotel.json' with { type: 'json' };
import record22 from './entities/cress-tech.json' with { type: 'json' };
import record23 from './entities/ctc.json' with { type: 'json' };
import record24 from './entities/dai-ichi-life-group.json' with { type: 'json' };
import record25 from './entities/dai-ichi-life.json' with { type: 'json' };
import record26 from './entities/daiichikosho.json' with { type: 'json' };
import record27 from './entities/daiki-suisan.json' with { type: 'json' };
import record28 from './entities/daiwa-securities.json' with { type: 'json' };
import record29 from './entities/digital-agency.json' with { type: 'json' };
import record30 from './entities/dwango.json' with { type: 'json' };
import record31 from './entities/enecom.json' with { type: 'json' };
import record32 from './entities/epark-relax.json' with { type: 'json' };
import record33 from './entities/eplus.json' with { type: 'json' };
import record34 from './entities/estore.json' with { type: 'json' };
import record35 from './entities/flex-gallery.json' with { type: 'json' };
import record36 from './entities/fujikura.json' with { type: 'json' };
import record37 from './entities/fujitsu.json' with { type: 'json' };
import record38 from './entities/furuno-electric.json' with { type: 'json' };
import record39 from './entities/furuno-systems.json' with { type: 'json' };
import record40 from './entities/ginpo-pack.json' with { type: 'json' };
import record41 from './entities/glory.json' with { type: 'json' };
import record42 from './entities/gmo-research-ai.json' with { type: 'json' };
import record43 from './entities/hanshin-expressway.json' with { type: 'json' };
import record44 from './entities/harada.json' with { type: 'json' };
import record45 from './entities/helpfeel.json' with { type: 'json' };
import record46 from './entities/hi-ho.json' with { type: 'json' };
import record47 from './entities/his-thailand.json' with { type: 'json' };
import record48 from './entities/hj-holdings.json' with { type: 'json' };
import record49 from './entities/hoya.json' with { type: 'json' };
import record50 from './entities/huistenbosch.json' with { type: 'json' };
import record51 from './entities/idc-frontier.json' with { type: 'json' };
import record52 from './entities/iij.json' with { type: 'json' };
import record53 from './entities/ikegami.json' with { type: 'json' };
import record54 from './entities/internet-disclosure.json' with { type: 'json' };
import record55 from './entities/iseto.json' with { type: 'json' };
import record56 from './entities/ishikawa-computer-center.json' with { type: 'json' };
import record57 from './entities/ites.json' with { type: 'json' };
import record58 from './entities/jaea.json' with { type: 'json' };
import record59 from './entities/jb-honshi.json' with { type: 'json' };
import record60 from './entities/jcom.json' with { type: 'json' };
import record61 from './entities/jgc-digital.json' with { type: 'json' };
import record62 from './entities/jogmec.json' with { type: 'json' };
import record63 from './entities/jtech-rokkasho.json' with { type: 'json' };
import record64 from './entities/kadokawa.json' with { type: 'json' };
import record65 from './entities/kanamoto.json' with { type: 'json' };
import record66 from './entities/kantsu.json' with { type: 'json' };
import record67 from './entities/kddi.json' with { type: 'json' };
import record68 from './entities/keio.json' with { type: 'json' };
import record69 from './entities/kinokuniya.json' with { type: 'json' };
import record70 from './entities/kokuyo.json' with { type: 'json' };
import record71 from './entities/kufu-company.json' with { type: 'json' };
import record72 from './entities/kurashiki-hampu.json' with { type: 'json' };
import record73 from './entities/kyusai.json' with { type: 'json' };
import record74 from './entities/lashinbang.json' with { type: 'json' };
import record75 from './entities/laurel.json' with { type: 'json' };
import record76 from './entities/lawson.json' with { type: 'json' };
import record77 from './entities/lean-body.json' with { type: 'json' };
import record78 from './entities/line-yahoo.json' with { type: 'json' };
import record79 from './entities/mazda.json' with { type: 'json' };
import record80 from './entities/mitsubishi-home.json' with { type: 'json' };
import record81 from './entities/mitsui-fudosan.json' with { type: 'json' };
import record82 from './entities/mk-system.json' with { type: 'json' };
import record83 from './entities/moneyforward.json' with { type: 'json' };
import record84 from './entities/monogatari.json' with { type: 'json' };
import record85 from './entities/moonstar.json' with { type: 'json' };
import record86 from './entities/morinaga-confectionery.json' with { type: 'json' };
import record87 from './entities/murauchi.json' with { type: 'json' };
import record88 from './entities/nagoya-container-committee.json' with { type: 'json' };
import record89 from './entities/nagoya-port-association.json' with { type: 'json' };
import record90 from './entities/naniwa-pump.json' with { type: 'json' };
import record91 from './entities/nexco-central.json' with { type: 'json' };
import record92 from './entities/nexco-east.json' with { type: 'json' };
import record93 from './entities/nexco-west.json' with { type: 'json' };
import record94 from './entities/nichirei.json' with { type: 'json' };
import record95 from './entities/nidec-instruments.json' with { type: 'json' };
import record96 from './entities/nidec-precision-vietnam.json' with { type: 'json' };
import record97 from './entities/nikkei-media-marketing.json' with { type: 'json' };
import record98 from './entities/nimoca.json' with { type: 'json' };
import record99 from './entities/nippon-rentacar-service.json' with { type: 'json' };

export const ENTITIES_PART_1 = {
  "2rinkan-yellowhat": record0,
  "abahouse-international": record1,
  "adastria": record2,
  "adventure": record3,
  "aflac-japan": record4,
  "ainokaze-toyama": record5,
  "aiphone-australia": record6,
  "aizawa-am": record7,
  "applynow": record8,
  "asahi": record9,
  "askul": record10,
  "atex": record11,
  "bilcom": record12,
  "bookoff-unnamed-subsidiary": record13,
  "casio": record14,
  "charm": record15,
  "chuden": record16,
  "citizen-watch": record17,
  "coconala": record18,
  "commune": record19,
  "core-concept-technologies": record20,
  "cosmos-hotel": record21,
  "cress-tech": record22,
  "ctc": record23,
  "dai-ichi-life-group": record24,
  "dai-ichi-life": record25,
  "daiichikosho": record26,
  "daiki-suisan": record27,
  "daiwa-securities": record28,
  "digital-agency": record29,
  "dwango": record30,
  "enecom": record31,
  "epark-relax": record32,
  "eplus": record33,
  "estore": record34,
  "flex-gallery": record35,
  "fujikura": record36,
  "fujitsu": record37,
  "furuno-electric": record38,
  "furuno-systems": record39,
  "ginpo-pack": record40,
  "glory": record41,
  "gmo-research-ai": record42,
  "hanshin-expressway": record43,
  "harada": record44,
  "helpfeel": record45,
  "hi-ho": record46,
  "his-thailand": record47,
  "hj-holdings": record48,
  "hoya": record49,
  "huistenbosch": record50,
  "idc-frontier": record51,
  "iij": record52,
  "ikegami": record53,
  "internet-disclosure": record54,
  "iseto": record55,
  "ishikawa-computer-center": record56,
  "ites": record57,
  "jaea": record58,
  "jb-honshi": record59,
  "jcom": record60,
  "jgc-digital": record61,
  "jogmec": record62,
  "jtech-rokkasho": record63,
  "kadokawa": record64,
  "kanamoto": record65,
  "kantsu": record66,
  "kddi": record67,
  "keio": record68,
  "kinokuniya": record69,
  "kokuyo": record70,
  "kufu-company": record71,
  "kurashiki-hampu": record72,
  "kyusai": record73,
  "lashinbang": record74,
  "laurel": record75,
  "lawson": record76,
  "lean-body": record77,
  "line-yahoo": record78,
  "mazda": record79,
  "mitsubishi-home": record80,
  "mitsui-fudosan": record81,
  "mk-system": record82,
  "moneyforward": record83,
  "monogatari": record84,
  "moonstar": record85,
  "morinaga-confectionery": record86,
  "murauchi": record87,
  "nagoya-container-committee": record88,
  "nagoya-port-association": record89,
  "naniwa-pump": record90,
  "nexco-central": record91,
  "nexco-east": record92,
  "nexco-west": record93,
  "nichirei": record94,
  "nidec-instruments": record95,
  "nidec-precision-vietnam": record96,
  "nikkei-media-marketing": record97,
  "nimoca": record98,
  "nippon-rentacar-service": record99,
} as Record<string, EntityClassification>;
