// Generated by scripts/classification-index.mjs; edit individual JSON records.
import type { EntityClassification } from '../classificationTypes';
import { ENTITIES_PART_1 } from './entities-index-part-1.ts';
import { ENTITIES_PART_2 } from './entities-index-part-2.ts';

export const ENTITIES = {
  ...ENTITIES_PART_1,
  ...ENTITIES_PART_2,
} as Record<string, EntityClassification>;
