// Generated by scripts/classification-index.mjs; edit individual JSON records.
import type { EntityClassification } from '../classificationTypes';
import record0 from './entities/adastria.json' with { type: 'json' };
import record1 from './entities/aflac-japan.json' with { type: 'json' };
import record2 from './entities/ainokaze-toyama.json' with { type: 'json' };
import record3 from './entities/aizawa-am.json' with { type: 'json' };
import record4 from './entities/applynow.json' with { type: 'json' };
import record5 from './entities/asahi.json' with { type: 'json' };
import record6 from './entities/askul.json' with { type: 'json' };
import record7 from './entities/atex.json' with { type: 'json' };
import record8 from './entities/bilcom.json' with { type: 'json' };
import record9 from './entities/casio.json' with { type: 'json' };
import record10 from './entities/charm.json' with { type: 'json' };
import record11 from './entities/chuden.json' with { type: 'json' };
import record12 from './entities/cosmos-hotel.json' with { type: 'json' };
import record13 from './entities/cress-tech.json' with { type: 'json' };
import record14 from './entities/ctc.json' with { type: 'json' };
import record15 from './entities/dwango.json' with { type: 'json' };
import record16 from './entities/estore.json' with { type: 'json' };
import record17 from './entities/fujikura.json' with { type: 'json' };
import record18 from './entities/fujitsu.json' with { type: 'json' };
import record19 from './entities/furuno-electric.json' with { type: 'json' };
import record20 from './entities/furuno-systems.json' with { type: 'json' };
import record21 from './entities/ginpo-pack.json' with { type: 'json' };
import record22 from './entities/glory.json' with { type: 'json' };
import record23 from './entities/hanshin-expressway.json' with { type: 'json' };
import record24 from './entities/harada.json' with { type: 'json' };
import record25 from './entities/his-thailand.json' with { type: 'json' };
import record26 from './entities/hj-holdings.json' with { type: 'json' };
import record27 from './entities/hoya.json' with { type: 'json' };
import record28 from './entities/huistenbosch.json' with { type: 'json' };
import record29 from './entities/idc-frontier.json' with { type: 'json' };
import record30 from './entities/iij.json' with { type: 'json' };
import record31 from './entities/internet-disclosure.json' with { type: 'json' };
import record32 from './entities/iseto.json' with { type: 'json' };
import record33 from './entities/ishikawa-computer-center.json' with { type: 'json' };
import record34 from './entities/ites.json' with { type: 'json' };
import record35 from './entities/jb-honshi.json' with { type: 'json' };
import record36 from './entities/jcom.json' with { type: 'json' };
import record37 from './entities/jtech-rokkasho.json' with { type: 'json' };
import record38 from './entities/kadokawa.json' with { type: 'json' };
import record39 from './entities/kanamoto.json' with { type: 'json' };
import record40 from './entities/kantsu.json' with { type: 'json' };
import record41 from './entities/kddi.json' with { type: 'json' };
import record42 from './entities/kinokuniya.json' with { type: 'json' };
import record43 from './entities/kokuyo.json' with { type: 'json' };
import record44 from './entities/kurashiki-hampu.json' with { type: 'json' };
import record45 from './entities/kyusai.json' with { type: 'json' };
import record46 from './entities/laurel.json' with { type: 'json' };
import record47 from './entities/line-yahoo.json' with { type: 'json' };
import record48 from './entities/mazda.json' with { type: 'json' };
import record49 from './entities/mitsubishi-home.json' with { type: 'json' };
import record50 from './entities/mk-system.json' with { type: 'json' };
import record51 from './entities/moneyforward.json' with { type: 'json' };
import record52 from './entities/morinaga-confectionery.json' with { type: 'json' };
import record53 from './entities/nagoya-container-committee.json' with { type: 'json' };
import record54 from './entities/nagoya-port-association.json' with { type: 'json' };
import record55 from './entities/naniwa-pump.json' with { type: 'json' };
import record56 from './entities/nexco-central.json' with { type: 'json' };
import record57 from './entities/nexco-east.json' with { type: 'json' };
import record58 from './entities/nexco-west.json' with { type: 'json' };
import record59 from './entities/nichirei.json' with { type: 'json' };
import record60 from './entities/nidec-instruments.json' with { type: 'json' };
import record61 from './entities/nidec-precision-vietnam.json' with { type: 'json' };
import record62 from './entities/nikkei-media-marketing.json' with { type: 'json' };
import record63 from './entities/nipro-china.json' with { type: 'json' };
import record64 from './entities/nssol.json' with { type: 'json' };
import record65 from './entities/ntt-business-solutions.json' with { type: 'json' };
import record66 from './entities/ntt-communications.json' with { type: 'json' };
import record67 from './entities/ntt-docomo.json' with { type: 'json' };
import record68 from './entities/ntt-marketing-act-procx.json' with { type: 'json' };
import record69 from './entities/ntt-nexia.json' with { type: 'json' };
import record70 from './entities/oiles.json' with { type: 'json' };
import record71 from './entities/prtimes.json' with { type: 'json' };
import record72 from './entities/restar-communications.json' with { type: 'json' };
import record73 from './entities/restar-device.json' with { type: 'json' };
import record74 from './entities/restar-electronics.json' with { type: 'json' };
import record75 from './entities/restar-solutions-support.json' with { type: 'json' };
import record76 from './entities/restar.json' with { type: 'json' };
import record77 from './entities/ricoh.json' with { type: 'json' };
import record78 from './entities/sakura-internet.json' with { type: 'json' };
import record79 from './entities/seed.json' with { type: 'json' };
import record80 from './entities/seiko.json' with { type: 'json' };
import record81 from './entities/sevennet-aidem.json' with { type: 'json' };
import record82 from './entities/sharp.json' with { type: 'json' };
import record83 from './entities/shinchosha.json' with { type: 'json' };
import record84 from './entities/shirohato.json' with { type: 'json' };
import record85 from './entities/shutoko.json' with { type: 'json' };
import record86 from './entities/sogo.json' with { type: 'json' };
import record87 from './entities/solpac.json' with { type: 'json' };
import record88 from './entities/sompo-japan.json' with { type: 'json' };
import record89 from './entities/sougyo.json' with { type: 'json' };
import record90 from './entities/sourcenext.json' with { type: 'json' };
import record91 from './entities/surugaya.json' with { type: 'json' };
import record92 from './entities/takamiya.json' with { type: 'json' };
import record93 from './entities/takara-belmont.json' with { type: 'json' };
import record94 from './entities/tci-us.json' with { type: 'json' };
import record95 from './entities/teikoku-databank.json' with { type: 'json' };
import record96 from './entities/tges.json' with { type: 'json' };
import record97 from './entities/times-mobility.json' with { type: 'json' };
import record98 from './entities/toko-foods.json' with { type: 'json' };
import record99 from './entities/tokyo-gas.json' with { type: 'json' };
import record100 from './entities/tokyu-livable.json' with { type: 'json' };
import record101 from './entities/tomoe-shokai.json' with { type: 'json' };
import record102 from './entities/toyota-connected.json' with { type: 'json' };
import record103 from './entities/toyota-mobility-service.json' with { type: 'json' };
import record104 from './entities/toyota-motor.json' with { type: 'json' };
import record105 from './entities/vitec-enesta.json' with { type: 'json' };
import record106 from './entities/vitec-vegetable-factory.json' with { type: 'json' };
import record107 from './entities/wantedly.json' with { type: 'json' };
import record108 from './entities/y4-com.json' with { type: 'json' };
import record109 from './entities/zeon.json' with { type: 'json' };
import record110 from './entities/zojirushi-taiwan.json' with { type: 'json' };
export const ENTITIES = {
  "adastria": record0,
  "aflac-japan": record1,
  "ainokaze-toyama": record2,
  "aizawa-am": record3,
  "applynow": record4,
  "asahi": record5,
  "askul": record6,
  "atex": record7,
  "bilcom": record8,
  "casio": record9,
  "charm": record10,
  "chuden": record11,
  "cosmos-hotel": record12,
  "cress-tech": record13,
  "ctc": record14,
  "dwango": record15,
  "estore": record16,
  "fujikura": record17,
  "fujitsu": record18,
  "furuno-electric": record19,
  "furuno-systems": record20,
  "ginpo-pack": record21,
  "glory": record22,
  "hanshin-expressway": record23,
  "harada": record24,
  "his-thailand": record25,
  "hj-holdings": record26,
  "hoya": record27,
  "huistenbosch": record28,
  "idc-frontier": record29,
  "iij": record30,
  "internet-disclosure": record31,
  "iseto": record32,
  "ishikawa-computer-center": record33,
  "ites": record34,
  "jb-honshi": record35,
  "jcom": record36,
  "jtech-rokkasho": record37,
  "kadokawa": record38,
  "kanamoto": record39,
  "kantsu": record40,
  "kddi": record41,
  "kinokuniya": record42,
  "kokuyo": record43,
  "kurashiki-hampu": record44,
  "kyusai": record45,
  "laurel": record46,
  "line-yahoo": record47,
  "mazda": record48,
  "mitsubishi-home": record49,
  "mk-system": record50,
  "moneyforward": record51,
  "morinaga-confectionery": record52,
  "nagoya-container-committee": record53,
  "nagoya-port-association": record54,
  "naniwa-pump": record55,
  "nexco-central": record56,
  "nexco-east": record57,
  "nexco-west": record58,
  "nichirei": record59,
  "nidec-instruments": record60,
  "nidec-precision-vietnam": record61,
  "nikkei-media-marketing": record62,
  "nipro-china": record63,
  "nssol": record64,
  "ntt-business-solutions": record65,
  "ntt-communications": record66,
  "ntt-docomo": record67,
  "ntt-marketing-act-procx": record68,
  "ntt-nexia": record69,
  "oiles": record70,
  "prtimes": record71,
  "restar-communications": record72,
  "restar-device": record73,
  "restar-electronics": record74,
  "restar-solutions-support": record75,
  "restar": record76,
  "ricoh": record77,
  "sakura-internet": record78,
  "seed": record79,
  "seiko": record80,
  "sevennet-aidem": record81,
  "sharp": record82,
  "shinchosha": record83,
  "shirohato": record84,
  "shutoko": record85,
  "sogo": record86,
  "solpac": record87,
  "sompo-japan": record88,
  "sougyo": record89,
  "sourcenext": record90,
  "surugaya": record91,
  "takamiya": record92,
  "takara-belmont": record93,
  "tci-us": record94,
  "teikoku-databank": record95,
  "tges": record96,
  "times-mobility": record97,
  "toko-foods": record98,
  "tokyo-gas": record99,
  "tokyu-livable": record100,
  "tomoe-shokai": record101,
  "toyota-connected": record102,
  "toyota-mobility-service": record103,
  "toyota-motor": record104,
  "vitec-enesta": record105,
  "vitec-vegetable-factory": record106,
  "wantedly": record107,
  "y4-com": record108,
  "zeon": record109,
  "zojirushi-taiwan": record110,
} as Record<string, EntityClassification>;
