// Generated by scripts/classification-index.mjs; edit individual JSON records.
import type { EntityClassification } from '../classificationTypes';
import record0 from './entities/nipro-china.json' with { type: 'json' };
import record1 from './entities/nssol.json' with { type: 'json' };
import record2 from './entities/ntt-business-solutions.json' with { type: 'json' };
import record3 from './entities/ntt-communications.json' with { type: 'json' };
import record4 from './entities/ntt-docomo.json' with { type: 'json' };
import record5 from './entities/ntt-marketing-act-procx.json' with { type: 'json' };
import record6 from './entities/ntt-nexia.json' with { type: 'json' };
import record7 from './entities/oiles.json' with { type: 'json' };
import record8 from './entities/prtimes.json' with { type: 'json' };
import record9 from './entities/rakuten-mobile.json' with { type: 'json' };
import record10 from './entities/resorttrust.json' with { type: 'json' };
import record11 from './entities/restar-communications.json' with { type: 'json' };
import record12 from './entities/restar-device.json' with { type: 'json' };
import record13 from './entities/restar-electronics.json' with { type: 'json' };
import record14 from './entities/restar-solutions-support.json' with { type: 'json' };
import record15 from './entities/restar.json' with { type: 'json' };
import record16 from './entities/ricoh.json' with { type: 'json' };
import record17 from './entities/sagawa-express.json' with { type: 'json' };
import record18 from './entities/sakura-internet.json' with { type: 'json' };
import record19 from './entities/sammy-networks.json' with { type: 'json' };
import record20 from './entities/scala-communications.json' with { type: 'json' };
import record21 from './entities/seed.json' with { type: 'json' };
import record22 from './entities/seicomart.json' with { type: 'json' };
import record23 from './entities/seidensha.json' with { type: 'json' };
import record24 from './entities/seiko.json' with { type: 'json' };
import record25 from './entities/sevennet-aidem.json' with { type: 'json' };
import record26 from './entities/sharp.json' with { type: 'json' };
import record27 from './entities/shinchosha.json' with { type: 'json' };
import record28 from './entities/shirohato.json' with { type: 'json' };
import record29 from './entities/shutoko.json' with { type: 'json' };
import record30 from './entities/sogo.json' with { type: 'json' };
import record31 from './entities/solpac.json' with { type: 'json' };
import record32 from './entities/sompo-japan.json' with { type: 'json' };
import record33 from './entities/sougyo.json' with { type: 'json' };
import record34 from './entities/sourcenext.json' with { type: 'json' };
import record35 from './entities/surugaya.json' with { type: 'json' };
import record36 from './entities/takamiya.json' with { type: 'json' };
import record37 from './entities/takara-belmont.json' with { type: 'json' };
import record38 from './entities/tci-us.json' with { type: 'json' };
import record39 from './entities/teikoku-databank.json' with { type: 'json' };
import record40 from './entities/temairazu.json' with { type: 'json' };
import record41 from './entities/tges.json' with { type: 'json' };
import record42 from './entities/thinca.json' with { type: 'json' };
import record43 from './entities/times-mobility.json' with { type: 'json' };
import record44 from './entities/toko-foods.json' with { type: 'json' };
import record45 from './entities/tokyo-gas.json' with { type: 'json' };
import record46 from './entities/tokyo-metro.json' with { type: 'json' };
import record47 from './entities/tokyu-livable.json' with { type: 'json' };
import record48 from './entities/tomoe-shokai.json' with { type: 'json' };
import record49 from './entities/toyota-connected.json' with { type: 'json' };
import record50 from './entities/toyota-mobility-service.json' with { type: 'json' };
import record51 from './entities/toyota-motor.json' with { type: 'json' };
import record52 from './entities/vitec-enesta.json' with { type: 'json' };
import record53 from './entities/vitec-vegetable-factory.json' with { type: 'json' };
import record54 from './entities/voising.json' with { type: 'json' };
import record55 from './entities/wantedly.json' with { type: 'json' };
import record56 from './entities/whiteessence.json' with { type: 'json' };
import record57 from './entities/world-wide-system.json' with { type: 'json' };
import record58 from './entities/y4-com.json' with { type: 'json' };
import record59 from './entities/zeon.json' with { type: 'json' };
import record60 from './entities/zojirushi-taiwan.json' with { type: 'json' };

export const ENTITIES_PART_2 = {
  "nipro-china": record0,
  "nssol": record1,
  "ntt-business-solutions": record2,
  "ntt-communications": record3,
  "ntt-docomo": record4,
  "ntt-marketing-act-procx": record5,
  "ntt-nexia": record6,
  "oiles": record7,
  "prtimes": record8,
  "rakuten-mobile": record9,
  "resorttrust": record10,
  "restar-communications": record11,
  "restar-device": record12,
  "restar-electronics": record13,
  "restar-solutions-support": record14,
  "restar": record15,
  "ricoh": record16,
  "sagawa-express": record17,
  "sakura-internet": record18,
  "sammy-networks": record19,
  "scala-communications": record20,
  "seed": record21,
  "seicomart": record22,
  "seidensha": record23,
  "seiko": record24,
  "sevennet-aidem": record25,
  "sharp": record26,
  "shinchosha": record27,
  "shirohato": record28,
  "shutoko": record29,
  "sogo": record30,
  "solpac": record31,
  "sompo-japan": record32,
  "sougyo": record33,
  "sourcenext": record34,
  "surugaya": record35,
  "takamiya": record36,
  "takara-belmont": record37,
  "tci-us": record38,
  "teikoku-databank": record39,
  "temairazu": record40,
  "tges": record41,
  "thinca": record42,
  "times-mobility": record43,
  "toko-foods": record44,
  "tokyo-gas": record45,
  "tokyo-metro": record46,
  "tokyu-livable": record47,
  "tomoe-shokai": record48,
  "toyota-connected": record49,
  "toyota-mobility-service": record50,
  "toyota-motor": record51,
  "vitec-enesta": record52,
  "vitec-vegetable-factory": record53,
  "voising": record54,
  "wantedly": record55,
  "whiteessence": record56,
  "world-wide-system": record57,
  "y4-com": record58,
  "zeon": record59,
  "zojirushi-taiwan": record60,
} as Record<string, EntityClassification>;
